---
title: "Statistics Practical"
author: "Abdullah Al Mahmud"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: false
  word_document:
    toc: true
    toc_depth: '3'
documentclass: report
geometry: margin=2cm
---

\newpage

\begingroup
\fontfamily{ppl}\fontsize{12}{16}\selectfont

# Practical Format

- Name of the Experiment
- Problem
- Solution (after page-break)

Leave some white space on the last page. 

## Solution part

- Theory/Methodology
- Equipment/Tools
- Calculation/Estimation/Computation
- Construction (if any)
- Interpretation/Explanation
- Precaution

# Construction of a Frequency Distribution

## Problem

Given below are daily earnings (BDT) of 30 freelancers. Construct a frequency distribution using a suitable class interval in a) inclusive and b) exclusive 
method and then interpret the table. 

\begin{center}

363 367 356 351 364 340 341 339 354 345 \\
349 349 352 356 359 335 364 348 363 350 \\
347 360 352 347 347 342 359 358 340 353

\end{center}

## Solution

### Theory

To make a frequency distribution we need to find 

i) The Range of data, $R = X_H - XL$
ii) No. of class (k). We may use the formula suggested by Sturges; $k = 1 + 3.322 \space log N$, where $N$ is the no. of values. 
iii) Class interval width, $C = \frac Rk$

We then create k classes eachh of C width and use tally symbols to determine the 
no. of values (frequency) of each class. 

### Tools

Pen, Pencil, Calculator, ...

### Estimation

### Interpretation

- Most freelancers earn between - and - taka.
- - to - taka are earned by the least number of people.
- Lowest incomes (- to -) are earned by -- no of people
- Highest earnings are made by 
- Overall pattern is this: 

# Determination of Arithmetic Mean, Combined Arithmetic Mean, Geometrci Mean, and Harmonic Mean from Grouped and Ungrouped Data.

# Construction of Histogram and Ogive

## Problem

Given below are daily wages of 30 workers in an agency. 

\begin{center}
\textbf{515, 833, 938, 511, 960, 968, 542, 842, 767, 694, 674, 955, 675, 972, 501, 987, 708, 846, 568, 721, 592, 867, 644, 966, 663, 551, 746, 942, 760, 601}
\end{center}

Draw a Histogram and an Ogive from the data and interpret.

## Solution

### Theory

A histogram is constructed from a frequency distribution with continuous class intervals. The frequencies corresponding to different classes are shown on the axis as bars, leaving no space or gap between the bars. 

# Determination of Quartiles, Deciles, and Percentiles

## Problem

Given below are temperatures (in degree Celsius) of a city in 30 random days in a year. 

\begin{center}
33.86, 34.83, 35.59, 31.66, 26.31, 26.90, 33.10, 26.52, 35.17, 25.21, 25.28, 28.38, 29.62, 30.69, 32.72, 30.00, 30.14, 27.97, 28.45, 35.93, 33.34, 29.07, 34.00, 27.55, 34.03, 33.76, 29.48, 31.24, 33.79, 33.41
\end{center}

Find the quartiles, 4th and 7th Decile, and 35th \& 87th Percentiles from the data and interpret. 

## Solution

### Theory

Determination of First Quartile

Let n = no. of observations

If n = odd

Location of first quartile = $\frac{n+1}{4}$th item 

Location of 2nd quartile = $\frac{2(n+1)}{4}$th item 

Other quantiles are determined in the same way. 

If n = even

Location of first quartile = $\frac{\frac n4 th + \frac{(n+1)}4th}{2}$

Location of 2nd quartile = $\frac{\frac {2n}4 th + \frac{2(n+1)}4th}{2}$

Other quantiles are determined similarly. 

The general formula to find the ith quantile, which divides the dataset into k parts.

\[
Q_i = \frac{i(n+1)}{k}th; \text{if n is odd}
\]

\[
Q_i = \frac{\frac{in}{k}th+(\frac{in}{k}+1)th}{2}; \text{if n is even}
\]


# Solution of Different Types of Problems Using Histogram and Ogive

## Problem 

The following are the scores of 80 applicants in a screening test given by an institution. 
\begin{table}[h]
\centering
\begin{tabular}{c|c|c|c|c|c|c|c|c|c|c}
Score & 45-49 & 50-54 & 55-59 & 60-64 & 65-69 & 70-74 & 75-79 & 80-84 & 84-89 & 90-94 \\ \hline
Frequency & 3 & 5 & 11 & 15 & 20 & 8 & 7 & 5 & 4 & 2
\end{tabular}
\end{table}


i. Draw an Ogive and therefrom find $Q3, D_4, and \space P_{47}$ and interpret.
ii. Construct a histogram from the data and find Mode. 

# Determination of First Four Moments from Data

## Problem

Temperature (in degree ceslsius) in Sylhet in first 10 days in May are given below:

29, 31, 30, 32, 30, 31, 28, 29, 34, 33

Find the first four central moments and the corresponding raw moments around 5. 

## Solution

### Theory

rth raw moment around a, $\displaystyle \mu_r'(a) = \frac{\sum_{i=1}^n (x_i-a)^r}{n}$

If we denote $d_i = x_i - a$, then

$\displaystyle \mu_r'(a) = \frac{\sum d^r}{n}$

rth central moment, $\displaystyle \mu_r = \frac{\sum_{i=1}^n (x_i-\bar x)^r}{n}$

#### Conversion from raw moments to central moments

We can use the binomial expansion. 

For the first moment, we use $(a+b)^1 = a+b$

For the second moment, We use $(a+b)^2 = a^2+2ab+b^2$

Similarly the subsequent moments are used to convert the origin moments. We can get the coefficients of binomial expansion from the pascal triangle.

To convert an origin `a` to another origin `k`, i.e. to convert $\mu_r'(a) \space to \space \mu_r'(k)$ 

we let $a^r = \mu_r'(a)$ and $b=a-k$

Thus, to, for example, convert $\mu_2(5)$ to $\mu_2'(8)$ we have

$b=a-k=5-8=-3$

$\mu_2'(8) = \mu_2'(5) + 2\mu_1'(5)b + b^2$

### Calculation

Make a table

### Central Moments

We find using the conversion 

# Determination of Skewness and Kurtosis and Their Types

## Problem

A shrimp producer wanted to get an insight into his shrimp production. To do so, he randomly collected weights of different shrimps in his farm.

\begin{table}[h]
\centering
\begin{tabular}{c|c|c|c|c|c}
Weight of shrimp (gm) & 10-20 & 20-30 & 30-40 & 40-50 & 50-60 \\ \hline
Frequency & 5 & 8 & 10 & 9 & 4
\end{tabular}
\end{table}

a. Estimate skewness and kurtosis of the data and interpret. 

\newpage

## Solution

### Theory

Coefficient of skewness, $\gamma_1 = \frac{\mu_3}{\sqrt{\mu_2^3}}$

Coefficient of kurtosis, $\gamma_2 = \beta_2 - 3 =  \frac{\mu_4}{\mu_2^2}-3$

# Construction of Box \& Whisker Plot and Five Numbers Summary And Analysis of Their Properties

## Problem

In the asteroid belt in the Solar System, there are estimated to be between 1.1 and 1.9 million objects with a radius above 500 m. The radii of the 25 largest bodies are given below.

\begin{center}
990, 980, 975, 924, 831, 824, 820, 780, 750, 731 \\
700, 700, 675, 658, 653, 609, 570, 515, 500, 466 \\
450, 432, 409, 400, 390
\end{center}

a. Display the data on a box and whisker plot and explain.
b. Determine the five number summary and explain.

## Solution

### Theory

To construct the Box and Whisker plot, we need to find the following values. 

$Median = \frac{n+1}{2}th$ term [since n is odd]

First quartile, $Q_1 = \frac{n+1}{4}th$ term 

Third quartile, $Q_3 = \frac{3(n+1)}{4}th$ term 

We also need to find the inner and outer fences using the Interquartile range (IQR)

$IQR = Q_3 - Q_1$

Inner fence: $Q_1 - 1.5 \times IQR$ and $Q_3 + 1.5 \times IQR$

Outer fence: $Q_1 - 3 \times IQR$ and $Q_3 + 3 \times IQR$

# Determination of General Trend of Time Series and Prediction 

# Exercises

# Second Paper

# Solution of Real-world Problems Concerning Expectation and Variance

## Problem

A box contains 5 red and 6 white balls. 3 balls are drawn at random from the box. X denotes the number of white balls drawn. Find the probability distribution of white balls drawn, the expected number of white balls drawn and the accompanying variance. 

## Solution

### Theory

To make the probability distribution, we need to find the probability of each outcome (in this case, number of white balls). There are 6 white balls and 11 balls in total.

Thus the probability function is:

$\displaystyle P(x) = \frac{^6C_x \times ?}{?}$

The expectation is computed using the formula

$\displaystyle E(X) = \sum_{i=1}^n x_i . p(x_i)$

ANd the variance is, $\displaystyle V(X) = E(X^2) - \{E(X)\}^2$

### Equipments

### Computation

#### The probability distribution

The possible values of x are 0, 1, 2, 3

| x | p(x)
|:---:|:---:|
|x = 0|

#### The Expectation

#### The Variance



# Fitting Binomial Distribution with the Help of a Frequency Distribution

## Problem

A coin is tossed 7 times and the result obtained is presented as follows:

| Number of head |0|1 |2| 3 | 4 | 5 | 6 | 7 |
|---------------|-----------|---|--|--|--|--|--|--|
|Frequency      |15|28|50|62|30|8|5|2|

Fit the above data with the help of Binomial distribution. 

## Solution

### Theory

Fitting a distribution involves finding the associated parameters of the distribution. 

The probability function of the Binomial distribution is $P(x) = ^nC_xp^xq^{n-x}$.

The expectation or mean is $E(X) = np$

The mean from the observed frequency distribution is $\displaystyle \bar X = \frac{\sum f_ix_i}{n}$.

### Tools

### Estimation

| Number of head (X) | Frequency ($f_i$) | $f_ix_i$ |
|:------------------:|:----------------:|:--------:|
|          0         |                  |          |
|          1         |                  |          |
|          2         |                  |          |
|          3         |                  |          |
|          4         |                  |          |
|          5         |                  |          |
|          6         |                  |          |
|          7         |                  |          |

Thus $\bar X =$

p = 

q = 

P(x) = ---



# Comparison of Expected and Observed Frequency of Binomial Distribution

## Problem

In a diagnostic center, each day 10 people are tested for High Blood Pressure. The result is summarized in the following table. 

| Number of diseased people |0|1 |2| 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|---------------|-----------|---|--|--|--|--|--|--|--|--|--|
|Frequency      |10|8|12|17|19|24|15|12|10|8|5|

Find the expected frequncies according to the Binomial model and compare with the
observed frequencies with a table and a graph. 

# Fitting Poisson Distribution with the Help of a Frequency Distribution

A frequency distribution is given below

|  Variable(X)  |  0 |  1 |  2 |  3 | 4 | 5 |
|:-------------:|:--:|:--:|:--:|:--:|:-:|:-:|
| Frequency (f) | 76 | 74 | 29 | 17 | 3 | 1 |

Fit the above data with the help of Poisson distribution.

# Comparison of Expected and Observed Frequency of Poisson Distribution

# Determination of Different Demographic Rates with Regards to The Population of Bangladesh


\endgroup