project:
  type: website
  output-dir: .

website:
  title: "Stat Mania Lectures"
  repo-url: https://github.com/mahmudstat/stat-lectures

format:
  revealjs:
    theme: sky
    transition: convex
    include-in-header: drawing-tools.html
    slide-number:  c/t
    navigation-mode: vertical
    controls-layout: bottom-right
    css:
    - css/styles.css
    - styles.css
    chalkboard: true
    logo: css/logo.png
    footer: "<a href='https://docs.statmania.info' target='_blank'>docs.statmania.info</a> | <b>Abdullah Al Mahmud</b>"
    plugins:
      - drawing



