---
title: "Measures of Dispersion"
author: Abdullah Al Mahmud
date: today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    transition: zoom
    reveal_plugins: ["chalkboard", "zoom", "menu"]
    reveal_options:
      chalkboard:
        theme: whiteboard
    self_contained: false
    lib_dir: libs
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Why Dispersion?

Which batter is better?

> - Batter A: 0, 100, 10, 10
> - Batter B: 20, 30, 25, 35

> - Dispersion measures variation
> - Needed alongside central tendency for comparison

# Is Dispersion Alone good?

> - Batter A: 0, 5, 10, 20, 4
> - Batter B: 10, 15, 12, 22, 16

# Graphically

<div class="container">
<div class="col">
```{r, echo=F, fig.width=6, fig.height=6}
par(bg="white")
source('../r/sketch_circle.R')
sketch_circle()
```
</div>
<div class="col">
</br>
</br>

- Which plot has the largest dispersion?
- Which plot has the smallest dispersion?

</div>
</div>

# Which is more scattered?

> - X: 10, 12, 15, 20
> - Y: 10, 50, 170, 470

# Measures of Dispersion

## Absolute Measures

> - Range
> - Mean Deviation
> - Quartile Deviation
> - Variance/Standard Deviation (Best)

## Relative Measures

> - Coefficient of Range
> - Coefficient of Mean Deviation
> - Coefficient of Quartile Deviation
> - Coefficient of Variance (Best)

# Estimation

Data: 10, 12, 23, 16, 17, 20, 15

## Range

$R = X_H - X_L$

## Mean Deviation (MD)

Around mean, $\displaystyle MD(\bar x)=\frac{1}{n}{\sum_{i=1}^{n} |x_i - \bar{x}|}$

> - For grouped data, $\displaystyle MD(\bar x) = \frac{1}{n}{\sum_{i=1}^{n} f_i|x_i - \bar{x}|}$
> - Similarly around median and mode (Me and Mo)

## Grouped Data

"Classified" is not a proper term

| Class Interval | Frequency |
|----------------|-----------|
| 10–19          | 5         |
| 20–29          | 12        |
| 30–39          | 18        |
| 40–49          | 10        |
| 50–59          | 6         |

## Variance and Standard Deviation

Variance, $\displaystyle \sigma^2 = \frac{1}{n} \sum_{i=1}^n (x_i - \bar{x})^2$

> - $\displaystyle \sigma^2 = \frac{\sum x_i^2}{n} - \left(\frac{\sum x_i}{n}\right)^2$
> - Mean of square - square of mean
> - $\bar {x^2} - (\bar x)^2$
> - SD = $\sqrt{Variance}$

## Coefficients

> - Coefficient of Range, $CR=\frac{X_H-X_L}{X_H+X_L}\times 100$
> - Coefficient of Mean Deviation, $CMD(\bar x) = \frac{MD(\bar x)}{\bar x}$
> - Coefficient of Quartile Deviation, $QD = \frac{Q_3-Q_1}{Q_3+Q_1} \times 100$
> - Coefficient of Variance (Best), $CV = \frac{\sigma}{\bar x} \times 100$

# Measures

> - $\displaystyle \text{Mean Deviation about Mean} = \frac{\sum_{i=1}^{N} |x_i - \bar{x}|}{N}$
> - $\displaystyle \text{Mean Deviation about Median} = \frac{1}{N} \sum_{i=1}^{N} |x_i - \text{Med}|$
> - $\displaystyle \text{Mean Deviation about Mode} = \frac{1}{N} \sum_{i=1}^{N} |x_i - \text{Mo}|$
> - $\displaystyle \text{Variance} = \frac{1}{N} \sum_{i=1}^{N} (x_i - \bar{x})^2$

## Variance Simplified

> - $\displaystyle \text{Variance} = \frac{1}{N} \sum_{i=1}^{N} (x_i - \bar{x})^2$
> - $\displaystyle \text{Variance} = \frac{1}{N} \left( \sum_{i=1}^{N} x_i^2 - 2\bar{x} \sum_{i=1}^{N} x_i + N\bar{x}^2 \right)$

## Variance Two Formulas


> - $\displaystyle \text{Variance} = \frac{1}{n} \sum_{i=1}^{n} (x_i - \bar{x})^2$
> - $\displaystyle \text{Variance} = \frac {\sum_{i=1}^{n}x_i^2}{n}   - (\bar{x})^2$
> - Mean of Square - Square of Mean

# Calculation

Suppose we have these values

12, 14, 15, 15, 19

Use absolute sign

|   x   |  \( x - \bar{x} \)  |  \( x - \text{Median} \)  |  \( x - \text{Mode} \)  |  \( x^2 \)  |  \( (x - \bar{x})^2 \)  |
|-------|----------------------|---------------------------|-------------------------|-------------|------------------------|
|  12   |   12 - 15 = -3       |   12 - 15 = -3            |   12 - 15 = -3          |  144        |   9                    |
|  14   |                      |                           |                         |             |                        |
|  15   |                      |                           |                         |             |                        |
|  15   |                      |                           |                         |             |                        |
|  19   |                      |                           |                         |             |                        |


## For Grouped Data

|    \(x \)  |  \( f_i \)  |
|-------|-------------|
|  12   |     1       |
|  14   |     1       |
|  15   |     2       |
|  19   |     1       |

## Calculation

|   \(x_i\)   |  \( f_i \)  |  \( f_i \times x_i \)  |  \( f_i \times x_i^2 \)  |
|---------|-------------|------------------------|--------------------------|
|    12   |     1       |                        |                          |
|    14   |     1       |                        |                          |
|    15   |     2       |                        |                          |
|    19   |     1       |                        |                          |


> - $\text{Variance} = \frac{\sum_{i=1}^{n} f_i (x_i - \bar{x})^2}{\sum_{i=1}^{n} f_i}$
> - $\text{Variance} = \frac{\sum_{i=1}^{n} f_i x_i^2}{\sum_{i=1}^{n} f_i} - \bar{x}^2$

