project:
  type: website
  output-dir: ../

website:
  title: "Stat Mania Docs"
  favicon: resources/logo.png
  repo-url: https://github.com/mahmudstat/stat-lectures
  navbar:
    background: light
    logo: resources/logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - href: index.qmd
        text: Home
      - text: "Learn"
        menu:
          - text: "Lectures"
            icon: "book"
            href: "lectures.qmd"
          - text: "Questions"
            icon: "archive-fill"
            href: "qbank.qmd"
      - text: "Resources"
        menu:
          - text: "Code Snippet"
            icon: "code-slash"
            href: "snippets.qmd"
          - text: "Statistics and Probability Notes"
            icon: "graph-up-arrow"
            href: "notes/scales-of-measurements.html"
          - text: "Nice Math"
            icon: "heart-pulse"
            href: "resources/Nice_Math.pdf"
          - text: "Stat Misc"
            icon: "dice-5"
            href: "resources.qmd"
          - text: "Stat Practical"
            icon: "dice-5"
            href: "resources/stat_practical.pdf"
      - text: "About"
        menu:
          - text: "Me"
            icon: "cursor"
            href: "https://www.thinkermahmud.com/"
          - text: "Portal"
            icon: "collection"
            href: "https://portal.statmania.info"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  revealjs:
    theme: sky
    css:
    - slide/css/styles.css
    - styles.css
    chalkboard: true
    logo: slide/css/logo.png
    footer: docs.statmania.info | Abdullah Al Mahmud | Use space key or arrows to move slides

