project:
  type: website
  output-dir: ../

website:
  title: "Stat Mania Lectures"
  repo-url: https://github.com/mahmudstat/stat-lectures
  navbar:
    background: light
    logo: resources/logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - href: index.qmd
        text: Home
      - lectures.qmd
      - qbank.qmd
      - resources.qmd
      - href: snippets.qmd
        text: Code Snippet
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/mahmudstat/stat-lectures/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/mahmudstat/stat-lectures/discussions"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true

  revealjs:
    theme: sky
    css:
    - slide/css/styles.css
    - styles.css
    chalkboard: true
    logo: slide/css/logo.png
    footer: docs.statmania.info | Abdullah Al Mahmud | Use space key or arrows to move slides

