project:
  type: website
  output-dir: ../

website:
  title: "Stat Mania Lectures"
  repo-url: https://github.com/mahmudstat/stat-lectures
  navbar:
    background: light
    logo: resources/logo.png
    logo-alt: "Stat Mania Logo."
    left:
      - href: index.qmd
        text: Home
      - lectures.qmd
      - qbank.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



