---
format: html
title: "Stat Mania Docs"
---

This websites mainly contains lectures slides and questions on statistics. It also contains some useful code snippets, covering linux command line, git, spreadsheet, among others.

<center>
<i style="font-size:10.5em; float: right; padding: 10px;" class="fa-solid fa-dice"></i>
</center>

All the lectures were initially made using [R programming language](https://www.r-project.org/) inside [Rstudio IDE](https://posit.co/download/rstudio-desktop/). The presentations were made using the [revealjs](https://revealjs.com/) package. Right now, the files are rendred using [Quarto](https://quarto.org/docs/presentations/revealjs/).

The following programming/markup languages or frameworks have been used in presentation generation:

* **HTML** (HyperText Markup Language): The standard markup language for creating web pages.
* **CSS** (Cascading Style Sheets): A stylesheet language used for designing web pages.
* **JavaScript**: A programming language enabling interactive web pages.
* **R**: A statistical programming language.
* **LaTeX**: A technical document preparation system.
* **Markdown**: A lightweight markup language for creating documents.
* **Git**: A distributed version control system for tracking changes in source code.
* **Bash**: A programming language and a command-line interpreter to interact with an operating system and run programs.
* **YAML** (YAML Ain't Markup Language): A human-readable data serialization language used for configuration files.
* **Quarto**: A technical publishing system.

## How to Use the presentations

- Press `space` or down-arrow ($\downarrow$) to go the next slide or see hidden contents.
- Press up-arrow ($\uparrow$) or `P` to go the previous slide.
- Press right arrow or left arrow to see next/previous chapter

See more [here](https://defkey.com/reveal-js-shortcuts)
